export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const REGISTER = 'REGISTER';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';

export const LOGOUT = 'LOGOUT';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const CREATE_PROJECT = 'CREATE_PROJECT';
export const SELECT_PROJECT_SUCCESS = 'SELECT_PROJECT_SUCCESS';

export const CREATE_ERROR = 'CREATE_ERROR';

export const DEPLOY_PROJECT = 'DEPLOY_PROJECT';
export const DEPLOY_PROJECT_SUCCESS = 'DEPLOY_PROJECT_SUCCESS';
